-- GENERATED by tools/gen.py from design/sheets/*.json. Edit the sheets, not this file.
local D = {}
D.areas = {
  ruins = {key = "ruins", name = "The Ruins", dd_folder = "crypts", ante_from = 0, ante_to = 2, colour_main = "#2B2F36", colour_light = "#4A5560", colour_dark = "#121417", contrast = 1.2},
  warrens = {key = "warrens", name = "The Warrens", dd_folder = "warrens", ante_from = 3, ante_to = 4, colour_main = "#3A2420", colour_light = "#6B3B30", colour_dark = "#160C0A", contrast = 1.2},
  weald = {key = "weald", name = "The Weald", dd_folder = "weald", ante_from = 5, ante_to = 6, colour_main = "#26301F", colour_light = "#4C5A33", colour_dark = "#0E120B", contrast = 1.2},
  cove = {key = "cove", name = "The Cove", dd_folder = "cove", ante_from = 7, ante_to = 8, colour_main = "#1C2A30", colour_light = "#2F5560", colour_dark = "#0A1114", contrast = 1.2},
  darkest = {key = "darkest", name = "The Darkest Dungeon", dd_folder = "darkestdungeon", ante_from = 9, ante_to = 99, colour_main = "#2A0F12", colour_light = "#5A1A1E", colour_dark = "#0A0304", contrast = 1.4},
}
D.areas_order = {"ruins", "warrens", "weald", "cove", "darkest"}
D.companion_files = {
  hero_info = {key = "hero_info", paths = {"heroes/{class}/{class}.info.darkest"}, parse = "info_darkest", fields = {"weapon.dmg_min", "weapon.dmg_max", "weapon.crit", "weapon.spd", "armour.hp", "armour.def"}, used_by = "heroes.stat_a, heroes.stat_b", fallback = "heroes.fallback_a / fallback_b"},
  hero_portrait = {key = "hero_portrait", paths = {"heroes/{class}/{class}_A/{class}_portrait_roster.png", "heroes/{class}/{class}_portrait_roster.png", "heroes/{class}/{class}_A/{class}_A_portrait_roster.png", "heroes/{class}/{class}_0/{class}_portrait_roster.png"}, parse = "png", fields = {"image"}, used_by = "atlas", fallback = "class initial drawn on a framed card"},
  hero_header = {key = "hero_header", paths = {"heroes/{class}/{class}_A/{class}_guild_header.png", "heroes/{class}/{class}_guild_header.png"}, parse = "png", fields = {"image"}, used_by = "atlas", fallback = "dark gradient background"},
  area_backdrop = {key = "area_backdrop", paths = {"dungeons/{area}/{area}.corridor_wall.{n}.png", "dungeons/{area}/{area}.corridor_wall_{n}.png", "dungeons/{area}/{area}.corridor_wall.0{n}.png"}, parse = "png", fields = {"image"}, used_by = "areas (backdrop)", fallback = "swirling background in the area's colours only"},
}
D.companion_files_order = {"hero_info", "hero_portrait", "hero_header", "area_backdrop"}
D.constants = {
  discard_stress = {key = "discard_stress", value = 3, unit = "stress", used_by = "on_discard", text = "Every discard adds Stress to every hero"},
  camp_relief = {key = "camp_relief", value = 15, unit = "stress", used_by = "on_round_end", text = "End of round: every hero loses this much Stress (camping)"},
  resolve_at = {key = "resolve_at", value = 100, unit = "stress", used_by = "add_stress", text = "Stress at which a hero's resolve is tested"},
  heart_attack_at = {key = "heart_attack_at", value = 200, unit = "stress", used_by = "add_stress", text = "An afflicted hero dies (the Joker is destroyed) at this Stress"},
  virtue_chance = {key = "virtue_chance", value = 25, unit = "percent", used_by = "resolve", text = "Chance the resolve test gives a Virtue instead of an Affliction (Darkest Dungeon's base is 25%)"},
  virtue_reset = {key = "virtue_reset", value = 40, unit = "stress", used_by = "resolve", text = "A virtuous hero's Stress drops to this"},
  virtue_rounds = {key = "virtue_rounds", value = 1, unit = "rounds", used_by = "on_round_end", text = "A Virtue lasts this many rounds"},
  clear_below = {key = "clear_below", value = 50, unit = "stress", used_by = "on_round_end", text = "An Affliction clears once Stress falls below this"},
  torch_min = {key = "torch_min", value = 0.25, unit = "alpha", used_by = "torch_alpha", text = "Vignette darkness with a calm party (and outside runs)"},
  torch_max = {key = "torch_max", value = 0.75, unit = "alpha", used_by = "torch_alpha", text = "Vignette darkness when the party's average Stress reaches resolve_at"},
  backdrop_alpha = {key = "backdrop_alpha", value = 0.45, unit = "alpha", used_by = "draw_backdrop", text = "How strongly the dungeon corridor art shows over the swirling background"},
  corridor_tiles = {key = "corridor_tiles", value = 12, unit = "files", used_by = "load_backdrops", text = "How many numbered corridor_wall images to look for per area"},
}
D.constants_order = {"discard_stress", "camp_relief", "resolve_at", "heart_attack_at", "virtue_chance", "virtue_reset", "virtue_rounds", "clear_below", "torch_min", "torch_max", "backdrop_alpha", "corridor_tiles"}
D.decks = {
  b_ddeck_expedition = {key = "b_ddeck_expedition", name = "Expedition Deck", order = 20, party = {"j_ddeck_crusader", "j_ddeck_highwayman", "j_ddeck_plague_doctor", "j_ddeck_vestal"}, art_from = "b_black", text = {"Start with a party of", "{C:attention}4 Darkest Dungeon heroes{}", "{C:inactive}Crusader, Highwayman,{}", "{C:inactive}Plague Doctor, Vestal{}"}},
}
D.decks_order = {"b_ddeck_expedition"}
D.heroes = {
  j_ddeck_crusader = {key = "j_ddeck_crusader", dd_class = "crusader", name = "Crusader", order = 1, rarity = 2, cost = 6, atlas_x = 0, ability = "smite", stat_a = "weapon.dmg_max", fallback_a = 12, scale_a = 1, stat_b = "-", fallback_b = 0, scale_b = 0, suit = "-", stress_per_hand = 6, stress_heal = 0, frame_colour = "#C9A227", text = {"{C:mult}+#1#{} Mult", "{C:inactive}(Smite: his weapon's max damage){}", "{C:purple}#2#{}"}},
  j_ddeck_highwayman = {key = "j_ddeck_highwayman", dd_class = "highwayman", name = "Highwayman", order = 2, rarity = 2, cost = 6, atlas_x = 1, ability = "pistol_shot", stat_a = "weapon.dmg_max", fallback_a = 10, scale_a = 5, stat_b = "weapon.crit", fallback_b = 5, scale_b = 4, suit = "-", stress_per_hand = 8, stress_heal = 0, frame_colour = "#8A5A2B", text = {"{C:chips}+#1#{} Chips", "{C:green}#3# in #4#{} chance of a", "{X:mult,C:white}X2{} Mult critical hit", "{C:purple}#2#{}"}},
  j_ddeck_plague_doctor = {key = "j_ddeck_plague_doctor", dd_class = "plague_doctor", name = "Plague Doctor", order = 3, rarity = 2, cost = 6, atlas_x = 2, ability = "noxious_blast", stat_a = "weapon.dmg_max", fallback_a = 7, scale_a = 1, stat_b = "-", fallback_b = 0, scale_b = 0, suit = "Clubs", stress_per_hand = 8, stress_heal = 0, frame_colour = "#5E7A3A", text = {"Each {C:clubs}Club{} held in hand", "gives {C:mult}+#1#{} Mult (Blight)", "{C:purple}#2#{}"}},
  j_ddeck_vestal = {key = "j_ddeck_vestal", dd_class = "vestal", name = "Vestal", order = 4, rarity = 2, cost = 6, atlas_x = 3, ability = "divine_grace", stat_a = "armour.hp", fallback_a = 24, scale_a = 1, stat_b = "-", fallback_b = 0, scale_b = 0, suit = "-", stress_per_hand = 7, stress_heal = 5, frame_colour = "#D8D2C0", text = {"{C:chips}+#1#{} Chips (her max HP)", "Each hand, other heroes", "lose {C:purple}#3#{} Stress", "{C:purple}#2#{}"}},
}
D.heroes_order = {"j_ddeck_crusader", "j_ddeck_highwayman", "j_ddeck_plague_doctor", "j_ddeck_vestal"}
D.hooks = {
  bootstrap = {key = "bootstrap", kind = "lovely_copy_append", target = "main.lua", purpose = "Load the mod's Lua after all game files, before love.load runs"},
  item_prototypes = {key = "item_prototypes", kind = "wrap_method", target = "Game.init_item_prototypes", purpose = "Add hero Jokers and the Expedition Deck to G.P_CENTERS and their pools"},
  localization = {key = "localization", kind = "wrap_global", target = "init_localization", purpose = "Add names and descriptions before Balatro parses them"},
  render_settings = {key = "render_settings", kind = "wrap_method", target = "Game.set_render_settings", purpose = "Build the hero atlas from Darkest Dungeon portraits"},
  set_sprites = {key = "set_sprites", kind = "wrap_method", target = "Card.set_sprites", purpose = "Show a hero's portrait (and afflicted/virtuous frame)"},
  calculate_joker = {key = "calculate_joker", kind = "wrap_method", target = "Card.calculate_joker", purpose = "Hero scoring and Stress"},
  ability_table = {key = "ability_table", kind = "wrap_method", target = "Card.generate_UIBox_ability_table", purpose = "Mark which hero's tooltip is being built"},
  card_ui = {key = "card_ui", kind = "wrap_global", target = "generate_card_ui", purpose = "Fill the hero tooltip numbers (stat, Stress, state)"},
  apply_to_run = {key = "apply_to_run", kind = "wrap_method", target = "Back.apply_to_run", purpose = "Expedition Deck hands out the party at run start"},
  background_colour = {key = "background_colour", kind = "wrap_global", target = "ease_background_colour", purpose = "Repaint Balatro's background in the current dungeon area's colours"},
  backdrop = {key = "backdrop", kind = "wrap_method", target = "Sprite.draw", purpose = "Draw the area's corridor art right after the background sprite (G.SPLASH_BACK), under the cards"},
  torchlight = {key = "torchlight", kind = "wrap_method", target = "Game.draw", purpose = "Draw the torchlight vignette over the finished frame"},
}
D.hooks_order = {"bootstrap", "item_prototypes", "localization", "render_settings", "set_sprites", "calculate_joker", "ability_table", "card_ui", "apply_to_run", "background_colour", "backdrop", "torchlight"}
D.states = {
  abusive = {key = "abusive", name = "Abusive", kind = "affliction", weight = 1, effect = "stress_others", value = 4, colour = "#B3261E", text = "Abusive: other heroes gain +4 Stress each hand"},
  hopeless = {key = "hopeless", name = "Hopeless", kind = "affliction", weight = 1, effect = "disable_ability", value = 0, colour = "#B3261E", text = "Hopeless: this hero's ability does nothing"},
  selfish = {key = "selfish", name = "Selfish", kind = "affliction", weight = 1, effect = "lose_money_eor", value = 2, colour = "#B3261E", text = "Selfish: lose $2 at end of round"},
  stalwart = {key = "stalwart", name = "Stalwart", kind = "virtue", weight = 1, effect = "no_stress_xmult", value = 1.5, colour = "#E8C547", text = "Stalwart: X1.5 Mult, gains no Stress"},
  powerful = {key = "powerful", name = "Powerful", kind = "virtue", weight = 1, effect = "xmult", value = 2, colour = "#E8C547", text = "Powerful: X2 Mult"},
}
D.states_order = {"abusive", "hopeless", "selfish", "stalwart", "powerful"}
return D
