"""Generate mod/DarkestDeck/ddeck/data.lua from the design sheets: one Lua table
(the row's 'struct') per sheet row, built from that row's columns."""
import json
from sheets import load, ROOT

def lua(v, ind=""):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, str): return json.dumps(v)  # JSON string escapes are valid Lua
    if isinstance(v, list): return "{" + ", ".join(lua(x) for x in v) + "}"
    if isinstance(v, dict):
        return "{" + ", ".join(f"{k} = {lua(x)}" for k, x in v.items()) + "}"
    raise TypeError(v)

def main():
    s = load()
    out = ["-- GENERATED by tools/gen.py from design/sheets/*.json. Edit the sheets, not this file.",
           "local D = {}"]
    for name in sorted(s):
        out.append(f"D.{name} = {{")
        for row in s[name]["rows"]:
            r = {c: row[c] for c in s[name]["columns"] if c != "verified"}
            out.append(f"  {row['key']} = {lua(r)},")
        out.append("}")
        out.append(f"D.{name}_order = {lua([r['key'] for r in s[name]['rows']])}")
    out.append("return D")
    p = ROOT / "mod/DarkestDeck/ddeck/data.lua"
    p.write_text("\n".join(out) + "\n")
    print("wrote", p.relative_to(ROOT))

if __name__ == "__main__": main()
